### ISSUE TITLE
Primary keys of aggregation tables are not case sensitive in mysql and mssql

### ISSUE THREAD

**Issue by minudika** [wso2/product-sp#1031]
**Description:**
Due to $subject, an error similar to the following is thrown when trying to insert a new record with the same values as an existing one, but different in the case of characters. (Eg; Key and KEY)

```
[2019-07-04 22:40:16,070] ERROR {org.wso2.siddhi.core.aggregation.IncrementalExecutor} - Exception occurred when writing to aggregation table of duration 'MONTHS'. This should be investigated as this can cause accuracy loss. org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Error in adding events to 'ApiUserPerAppAgg_MONTHS' store: Duplicate entry '1548979200000-apim-analytics-01-1548979200000-/t/wso2um/products' for key 'PRIMARY'
at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:587)
at org.wso2.siddhi.core.table.record.AbstractRecordTable.add(AbstractRecordTable.java:98)
at org.wso2.siddhi.core.table.Table.addEvents(Table.java:139)
at org.wso2.siddhi.core.aggregation.IncrementalExecutor.lambda$dispatchEvents$2(IncrementalExecutor.java:269)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.BatchUpdateException: Duplicate entry '1548979200000-apim-analytics-01-1548979200000-/t/wso2um/products' for key 'PRIMARY'
at sun.reflect.GeneratedConstructorAccessor79.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.Util.getInstance(Util.java:408)
at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
at com.zaxxer.hikari.proxy.StatementProxy.executeBatch(StatementProxy.java:127)
at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeBatch(HikariPreparedStatementProxy.java)
at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.batchExecuteQueriesWithRecords(RDBMSEventTable.java:1496)
at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:584)
... 6 more
```

**Comment by apercova** [comment]
The fix has been released within this patch: `WSO2 Carbon 5.X.X Update 2019-04-27`  
Pathc description stands:

`
This update introduces a new property called 'use.binary' to siddhi-store-RDBMS configs. This property
allows users to use collation for string attributes. By default it's false and collation is not used.
'latin1_bin' and 'SQL_Latin1_General_CP1_CS_AS' are used as collations by default for MySQL and
Microsoft SQL database types respectively.

If you encounter similar issues like https://github.com/wso2/product-sp/issues/1031, set this property
true for the relevant table in your siddhi app. If you are using a database type other than MySQL and
MS SQL you will need to add the collation property separately in the RDBMS configs.

Also, this property will be applied when the table is getting created. Therefore if you need to add a
collation for an existing table, you need to alter that table by providing the necessary collation.
Eg: ALTER TABLE USERS CHANGE USER_NAME USER_NAME VARCHAR(50) BINARY;
`  
Is this applicable to API Analytics? If true, I wonder where to configure `use.binary` property on  API Analytics.

**Comment by niveathika** [comment]
@apercova this has to be applied to the @store annotation in the relevant siddhi apps.

@minudika Was this fix ported to the master branch? For siddhi 5.x.x

**Comment by apercova** [comment]
Thankyou @niveathika for your help. 👍
