### ISSUE TITLE
Cannot find LdapContextFactory on server startup

### ISSUE THREAD

**Issue by lasanthaS** [wso2/product-sp#1057]
**Description:**
When an LDAP connection string is set up for a database in the `deployment.yaml`, the server startup fails with the following exception.

```
Caused by: java.sql.SQLRecoverableException: IO Error: JNDI Package failure javax.naming.NoInitialContextException: Cannot find the InitialContextFactory com.sun.jndi.ldap.LdapCtxFactory.
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	... 15 more
Caused by: oracle.net.ns.NetException: JNDI Package failure javax.naming.NoInitialContextException: Cannot find the InitialContextFactory com.sun.jndi.ldap.LdapCtxFactory.
	at oracle.net.jndi.JndiAttrs.<init>(JndiAttrs.java:170)
	at oracle.net.resolver.AddrResolution.<init>(AddrResolution.java:233)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:233)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
```

**Affected Product Version:**
SP 4.2.0

**Comment by lasanthaS** [comment]
Fixed by https://github.com/wso2/carbon-jndi/pull/45
