### ISSUE TITLE
Exception is occurred once delete a feed simulation 

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#200]
**Description:**
Following exception occurred once delete exiting feed simulation. 
```
osgi> [2017-11-28 01:10:50,661] ERROR {org.wso2.carbon.event.simulator.core.internal.util.SimulationConfigUploader} - Error occurred while reading the simulation configuration 'SiddhiSimulator'. java.nio.file.NoSuchFileException: /Users/cjayawardena/Documents/Testing/Analytics/wso2sp-4.0.0-beta/wso2/editor/deployment/simulation-configs/SiddhiSimulator.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at org.wso2.carbon.event.simulator.core.internal.util.SimulationConfigUploader.getSimulationConfig(SimulationConfigUploader.java:124)
	at org.wso2.carbon.event.simulator.core.impl.FeedApiServiceImpl.getFeedSimulations(FeedApiServiceImpl.java:159)
	at org.wso2.carbon.event.simulator.core.api.FeedApi.getFeedSimulations(FeedApi.java:104)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:185)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:142)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:249)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$58(MSF4JMessageProcessor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Suggested Labels:**
Editor, Feed Simulation

**Suggested Assignees:**
suho@wso2.com

**Affected Product Version:**
wso2sp-4.0.0-beta
**OS, DB, other environment details and versions:**    
Mac OSX
**Steps to reproduce:**
1. Create a feed simulation
2. Delete the created simulation without even starting/running it.

**Comment by suhothayan** [comment]
@ramindu90 please verify this issue

**Comment by ramindu90** [comment]
@suhothayan: it is reproducable. @erangatl will look into this

**Comment by sajithshn** [comment]
This is fixed
