### ISSUE TITLE
NPE on editor shutdown forcefully

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#209]
**Description:**
NPE occurred when shutdown hook triggered using Ctrl+C on the console. 

**Suggested Labels:**
Editor

**Suggested Assignees:**
suho@wso2.com

**Affected Product Version:**
wso2sp-4.0.0-beta2
**OS, DB, other environment details and versions:**    
Mac OSX
**Steps to reproduce:**
1. Shutdown the editor hitting Ctrl+C on the console while event simulator is running.
Below exception can be seen and better to handle NPE
```
^C[2017-12-02 17:25:13,492]  INFO {org.wso2.carbon.siddhi.editor.core.internal.ServiceComponent} - Service Component is deactivated
[2017-12-02 17:25:13,501]  INFO {org.wso2.carbon.stream.processor.core.internal.ServiceComponent} - Service Component is deactivated
[2017-12-02 17:25:13,506]  INFO {org.wso2.carbon.event.simulator.core.api.SingleApi} - Single Event Simulator service component is deactivated
[2017-12-02 17:25:13,520]  INFO {org.wso2.carbon.stream.processor.statistics.api.StatisticsApi} - org.wso2.carbon.stream.processor.statistics.api.StatisticsApi service component has stop.
[2017-12-02 17:25:13,523]  INFO {org.wso2.carbon.stream.processor.statistics.api.SystemDetailsApi} - SystemDetailsApi has been stop.
[2017-12-02 17:25:13,534]  INFO {org.wso2.carbon.siddhi.metrics.core.service.MetricsServiceComponent} - MetricsServiceComponent has been stop.
[2017-12-02 17:25:13,535]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Removed endpoint : /console
Exception in thread "pool-3-thread-3" java.lang.NullPointerException
	at org.wso2.carbon.event.simulator.core.service.EventSimulator.eventSimulation(EventSimulator.java:286)
	at org.wso2.carbon.event.simulator.core.service.EventSimulator.run(EventSimulator.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2017-12-02 17:25:13,544]  INFO {org.wso2.carbon.metrics.core.reporter.impl.AbstractReporter} - Stopped JMX reporter for Metrics
[2017-12-02 17:25:13,544]  INFO {org.wso2.msf4j.analytics.metrics.MetricsComponent} - Metrics Component is deactivated
[2017-12-02 17:25:13,549]  INFO {org.wso2.carbon.event.simulator.core.api.DatabaseApi} - Event Simulator database service component is deactivated
```

**Comment by suhothayan** [comment]
Cannot reproduce this on 4.0.0 beta2 pack
