### ISSUE TITLE
update and updateorInsert throws a NullPointerException

### ISSUE THREAD

**Issue by tharindulak** [wso2/product-sp#211]
**Description:**

@Store(type='solr', collection='SweetProductionTable', zookeeper.url='localhost:9983', shards='2', replicas='2', schema='name string stored,amount double stored')
@PrimaryKey("name")
define table SweetProductionTable (name string, amount double);

/* Updating events*/
@info(name = 'query3')
from updateSweetProductionStream
update SweetProductionTable 
on SweetProductionTable.name == name ;

when trying to insert events into solr store using the above Siddhi query, it throws an error as 

[2017-12-04_17-03-03_782] ERROR {org.wso2.carbon.siddhi.editor.core.internal.DebuggerEventStreamService} - Error when pushing events to Siddhi debugger engine
java.lang.NullPointerException
	at org.wso2.extension.siddhi.store.solr.SolrTable.upsertSolrDocuments(SolrTable.java:288)
	at org.wso2.extension.siddhi.store.solr.SolrTable.update(SolrTable.java:252)
	at org.wso2.siddhi.core.table.record.AbstractRecordTable.update(AbstractRecordTable.java:257)
	at org.wso2.siddhi.core.table.Table.updateEvents(Table.java:247)
	at org.wso2.siddhi.core.query.output.callback.UpdateTableCallback.send(UpdateTableCallback.java:71)
	at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
	at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)
	at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:91)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:187)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:97)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:133)
	at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:151)
	at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:358)
	at org.wso2.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)
	at org.wso2.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:44)
	at org.wso2.siddhi.core.stream.input.InputHandler.send(InputHandler.java:61)
	at org.wso2.carbon.siddhi.editor.core.internal.DebuggerEventStreamService.pushEvent(DebuggerEventStreamService.java:70)
	at org.wso2.carbon.event.simulator.core.internal.generator.SingleEventGenerator.sendEvent(SingleEventGenerator.java:84)
	at org.wso2.carbon.event.simulator.core.impl.SingleApiServiceImpl.runSingleSimulation(SingleApiServiceImpl.java:30)
	at org.wso2.carbon.event.simulator.core.api.SingleApi.runSingleSimulation(SingleApi.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:185)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:142)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:249)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$58(MSF4JMessageProcessor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by suhothayan** [comment]
@gimantha  is this fixed?

**Comment by gimantha** [comment]
This was caused because of usage of a wrong solr version (7.x.x instead of 6.x.x). This can not be reproduced with solr 6.x.x
