### ISSUE TITLE
Exception when starting SP 4.0.0 Beta 2 in Mac

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#212]
**Description:**
Error on startup 

**Affected Product Version:**
4.0 beta 2 

**OS, DB, other environment details and versions:**    
Mac OSX Sierra
Java jdk1.8.0_152

**Steps to reproduce:**
run editor.sh

suho@Suhos-MacBook-Pro-2:~/wso2/packs/sp/wso2sp-4.0.0-beta2$ ./bin/editor.sh
Using Java version: CurrentJDK
JAVA_HOME environment variable is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
CARBON_HOME environment variable is set to /Users/suho/wso2/packs/sp/wso2sp-4.0.0-beta2
RUNTIME_HOME environment variable is set to /Users/suho/wso2/packs/sp/wso2sp-4.0.0-beta2/wso2/editor
[2017-12-05 1:25:59,746]  INFO {org.wso2.carbon.launcher.extensions.OSGiLibBundleDeployerUtils updateOSGiLib} - Successfully updated the OSGi bundle information of Carbon Runtime: editor
2017-12-05 01:26:10,365 main ERROR Error processing element EditorConsole ([Appenders: null]): CLASS_NOT_FOUND
2017-12-05 01:26:10,419 main ERROR Unable to locate appender "EditorConsole" for logger config "root"
2017-12-05 01:26:15,437 ManagedService Update Queue ERROR Error processing element EditorConsole ([Appenders: null]): CLASS_NOT_FOUND
2017-12-05 01:26:15,447 ManagedService Update Queue ERROR Unable to locate appender "EditorConsole" for logger config "root"
osgi> org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; osgi.identity="org.ops4j.pax.logging.pax-logging-log4j2"; type="osgi.bundle"; version:Version="1.10.0" [id=4] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:453)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
	at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.wso2.carbon.launcher.CarbonServer.loadInitialBundles(CarbonServer.java:242)
	at org.wso2.carbon.launcher.CarbonServer.start(CarbonServer.java:83)
	at org.wso2.carbon.launcher.Main.main(Main.java:87)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 22 more
[2017-12-05 01:26:26,249]  WARN {org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager} - Adding a required OSGi service capability to component, but specified startup component is not available, component-name: carbon-transport-mgt and capability-name: org.wso2.carbon.deployment.engine.DeploymentService.
[2017-12-05 01:26:26,293]  INFO {org.wso2.msf4j.internal.websocket.WebSocketServerSC} - All required capabilities are available of WebSocket service component is available.
[2017-12-05 01:26:26,294]  INFO {org.wso2.carbon.analytics.idp.client.core.internal.IdPClientServiceComponent} - IdPClientServiceComponent is activated...
[2017-12-05 01:26:26,306]  INFO {org.wso2.carbon.metrics.core.config.model.JmxReporterConfig} - Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2017-12-05 01:26:26,320]  INFO {org.wso2.carbon.metrics.core.reporter.impl.AbstractReporter} - Started JMX reporter for Metrics
[2017-12-05 01:26:26,426]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary SSL Transport on port : 9715
[2017-12-05 01:26:26,427]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary TCP Transport on port : 9615
[2017-12-05 01:26:26,483]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift Server started at 0.0.0.0
[2017-12-05 01:26:26,491]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift SSL port : 7714
[2017-12-05 01:26:26,493]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift port : 7614
[2017-12-05 01:26:26,495]  INFO {org.wso2.carbon.databridge.core.internal.DataBridgeDS} - Successfully deployed Agent Server
[2017-12-05 01:26:26,505]  INFO {org.wso2.msf4j.analytics.metrics.MetricsComponent} - Metrics Component is activated
[2017-12-05 01:26:26,510]  INFO {org.wso2.carbon.databridge.agent.internal.DataAgentDS} - Successfully deployed Agent Server
[2017-12-05 01:26:26,531]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Endpoint Registered : /console
[2017-12-05 01:26:26,540]  INFO {org.wso2.carbon.siddhi.metrics.core.service.MetricsServiceComponent} - MetricsServiceComponent has been activated.
[2017-12-05 01:26:26,547]  INFO {com.zaxxer.hikari.HikariDataSource} - HikariPool-0 - is starting.
[2017-12-05 01:26:26,567]  INFO {org.wso2.carbon.stream.processor.statistics.api.SystemDetailsApi} - SystemDetailsApi has been activated.
[2017-12-05 01:26:26,739]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.msf4j.swagger.SwaggerDefinitionService@54657dd2
[2017-12-05 01:26:26,742]  INFO {org.wso2.carbon.cluster.coordinator.rdbms.internal.RDBMSCoordinationServiceComponent} - Cluster coordination has been disabled. Enable it in deployment.yaml to use the clustering service
[2017-12-05 01:26:26,752]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.msf4j.swagger.SwaggerDefinitionService@6428591a
[2017-12-05 01:26:26,838]  INFO {org.wso2.carbon.siddhi.editor.core.internal.ServiceComponent} - Editor Started on : http://192.168.1.5:9390/editor
[2017-12-05 01:26:26,874]  INFO {org.wso2.carbon.event.simulator.core.service.CSVFileDeployer} - CSV file deployer initiated.
[2017-12-05 01:26:26,876]  INFO {org.wso2.carbon.event.simulator.core.service.SimulationConfigDeployer} - Simulation config deployer initiated.
[2017-12-05 01:26:26,877]  INFO {org.wso2.carbon.siddhi.editor.core.internal.WorkspaceDeployer} - Workspace artifact deployer initiated.
[2017-12-05 01:26:26,880]  INFO {org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer} - Stream Processor Deployer Initiated
[2017-12-05 01:26:26,884]  INFO {org.wso2.carbon.stream.processor.core.internal.ServiceComponent} - Service Component is activated
[2017-12-05 01:26:26,911]  INFO {org.wso2.carbon.siddhi.store.api.rest.StoresApi} - Siddhi Store REST API Started...
[2017-12-05 01:26:26,921]  INFO {org.wso2.carbon.stream.processor.statistics.api.StatisticsApi} - org.wso2.carbon.stream.processor.statistics.api.StatisticsApi service component has  started.
[2017-12-05 01:26:26,970]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.DatabaseApi@72319b7
[2017-12-05 01:26:26,972]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.DatabaseApi@72319b7
[2017-12-05 01:26:26,979]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.FeedApi@33f1068b
[2017-12-05 01:26:26,981]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.FeedApi@33f1068b
[2017-12-05 01:26:26,991]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.FilesApi@618e8f0b
[2017-12-05 01:26:26,994]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.FilesApi@618e8f0b
[2017-12-05 01:26:27,000]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.core.api.HaApi@184fcfe8
[2017-12-05 01:26:27,004]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.core.api.HaApi@184fcfe8
[2017-12-05 01:26:27,012]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.core.api.SiddhiAppsApi@5b8f7e57
[2017-12-05 01:26:27,016]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.core.api.SiddhiAppsApi@5b8f7e57
[2017-12-05 01:26:27,023]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.statistics.api.SystemDetailsApi@4ac9cae5
[2017-12-05 01:26:27,026]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.statistics.api.SystemDetailsApi@4ac9cae5
[2017-12-05 01:26:27,030]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.SingleApi@65d827ce
[2017-12-05 01:26:27,035]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.event.simulator.core.api.SingleApi@65d827ce
[2017-12-05 01:26:27,047]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.siddhi.editor.core.internal.ServiceComponent@c3b6db2
[2017-12-05 01:26:27,051]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.siddhi.editor.core.internal.ServiceComponent@c3b6db2
[2017-12-05 01:26:27,056]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.siddhi.store.api.rest.StoresApi@4988b2da
[2017-12-05 01:26:27,059]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.siddhi.store.api.rest.StoresApi@4988b2da
[2017-12-05 01:26:27,077]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.statistics.api.StatisticsApi@3d21db36
[2017-12-05 01:26:27,082]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: org.wso2.carbon.stream.processor.statistics.api.StatisticsApi@3d21db36
[2017-12-05 01:26:27,092]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
[2017-12-05 01:26:35,936]  INFO {org.wso2.carbon.transport.http.netty.listener.ServerConnectorController} - Started listener http-9390
[2017-12-05 01:26:35,937]  INFO {org.wso2.carbon.transport.http.netty.listener.ServerConnectorController} - HTTP Interface default starting on host  0.0.0.0 and port 9390
[2017-12-05 01:26:35,938]  INFO {org.wso2.carbon.transport.http.netty.listener.ServerConnectorController} - Started listener https-9743
[2017-12-05 01:26:35,939]  INFO {org.wso2.carbon.transport.http.netty.listener.ServerConnectorController} - HTTPS Interface https starting on host  0.0.0.0 and port 9743
[2017-12-05 01:26:35,940]  INFO {org.wso2.carbon.transport.http.netty.internal.HTTPTransportServiceComponent} - All CarbonHTTPServerInitializers are available
[2017-12-05 01:26:35,941]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Stream Processor started in 41.620 sec

**Comment by suhothayan** [comment]
This is because of the issue in Mac JVM hostname resolution

**Comment by niruhan** [comment]
follow the solution at http://stackoverflow.com/a/33289897/2728768 and add <your mac name>.local after "127.0.0.1   localhost" and "::1         localhost"
