### ISSUE TITLE
[Improvement] [SiddhiApp- deployment] - Error message thrown at worker startup if Siddhi app saved and open as a file

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-sp#40]
**Description:** 
An error message thrown when start the worker if Siddhi app is open as a file but already saved

**Steps to recreate:**
- Configure a valid Siddhi app
- Open above configuration file (it should be saved - no unsaved data should be there)
- Run the worker node

`[2017-08-28 16:41:11,045] ERROR {org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer} - Error: File extension not supported for file name siddhiapptest1.siddhi~. Support only.siddhi . org.wso2.carbon.stream.processor.core.internal.exception.SiddhiAppDeploymentException: Error: File extension not supported for file name siddhiapptest1.siddhi~. Support only.siddhi .
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:95)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:159)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:266)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine$$Lambda$152/944746201.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:257)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:110)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:106)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:212)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$51(StartupComponentManager.java:238)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager$$Lambda$103/783859647.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:224)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
`
**Suggestion:** Can we improve it to get rid of error message

**Comment by suhothayan** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/683
