### ISSUE TITLE
When deploying siddhi app(s) with multiple sources which uses polling tasks, an exception is occured

### ISSUE THREAD

**Issue by minudika** [wso2/product-sp#463]
**Description:**
When deploying siddhi app(s) with multiple sources which uses polling tasks  (file, email etc ..) an exception is thrown similar to the following.

[2018-01-25 14:00:53,881] ERROR {org.wso2.carbon.connector.framework.server.polling.PollingTaskRunner} - Exception occurred while scheduling job org.quartz.ObjectAlreadyExistsException: Unable to store Trigger with name: 'scheduledPoll' and group: 'group1', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeTrigger(RAMJobStore.java:415)
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:252)
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
	at org.wso2.carbon.connector.framework.server.polling.PollingTaskRunner.start(PollingTaskRunner.java:74)
	at org.wso2.carbon.connector.framework.server.polling.PollingServerConnector.start(PollingServerConnector.java:57)
	at org.wso2.carbon.transport.remotefilesystem.server.connector.contractimpl.RemoteFileSystemServerConnectorImpl.start(RemoteFileSystemServerConnectorImpl.java:75)
	at org.wso2.extension.siddhi.io.file.FileSource.deployServers(FileSource.java:537)
	at org.wso2.extension.siddhi.io.file.FileSource.connect(FileSource.java:370)
	at org.wso2.siddhi.core.stream.input.source.Source.connectWithRetry(Source.java:130)
	at org.wso2.siddhi.core.SiddhiAppRuntime.start(SiddhiAppRuntime.java:336)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:280)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:81)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:170)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Suggested Labels:**
Bug

**Suggested Assignees:**
@minudika

**Affected Product Version:**
4.0.0

**Steps to reproduce:**
Create two siddhi apps using file sources which uses **dir.uri** and deploy them.

**Comment by etalaq** [comment]
I'm not sure if this applies here but just sharing incase helps:

https://stackoverflow.com/questions/25890202/unable-to-store-trigger-with-name-trigger1-and-group-group1-because-one-a

**Comment by minudika** [comment]
Hi @etalaq ,

Thanks for the support. 
Yes. That's the solution we have implemented in carbon-polling-core.
Previously every trigger was created with the same id which had been hard coded.
That's the reason for the above-reported exception.
Now it has been fixed by introducing an auto-generated id.
We will bump the necessary dependency versions in the relevant siddhi-io-* extensions soon.

**Comment by sajithshn** [comment]
This is fixed
