### ISSUE TITLE
NPE issue in distributed deployment manager node.

### ISSUE THREAD

**Issue by ksdperera** [wso2/product-sp#529]
**Description:**
In the distributed cluster and start only the master node throw a NPE exception:

```
[2018-03-26 07:13:42,109]  WARN {org.wso2.carbon.cluster.coordinator.rdbms.RDBMSMemberEventListenerTask} - Error occurred while reading membership events. java.lang.NullPointerException
	at org.wso2.carbon.sp.jobmanager.core.CoordinatorChangeListener.memberAdded(CoordinatorChangeListener.java:43)
	at org.wso2.carbon.cluster.coordinator.rdbms.RDBMSMemberEventListenerTask.notifyMemberAdditionEvent(RDBMSMemberEventListenerTask.java:136)
	at org.wso2.carbon.cluster.coordinator.rdbms.RDBMSMemberEventListenerTask.run(RDBMSMemberEventListenerTask.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SP 4.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Setup Master node in the Distributed cluster mode with Mysql Database.

**Related Issues:**

**Comment by this** [comment]
As per offline discussion with @ksdperera , issue is present in SP-4.3.0
