### ISSUE TITLE
getRegisteredSinkHandlers()Ljava/util/HashMap;

### ISSUE THREAD

**Issue by dzatloukal** [wso2/product-sp#672]
**Description:**
When running two nodes of SP in HA, I have following errors on both nodes.

1. When passive node want to borrow state from active node

```
INFO {org.wso2.carbon.stream.processor.core.ha.HAManager} - Passive Node: Borrowing state from active node after 10 seconds
WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.NoSuchMethodError: org.wso2.siddhi.core.stream.output.sink.SinkHandlerManager.getRegisteredSinkHandlers()Ljava/util/HashMap;
	at org.wso2.carbon.stream.processor.core.impl.HaApiServiceImpl.haOutputSyncTimestampGet(HaApiServiceImpl.java:58)
```

2. When passive node become active (and then I have two active nodes in cluster...)
```
INFO {org.wso2.carbon.stream.processor.core.ha.HAEventListener} - HA Deployment: This Node is now the Active Node
WARN {org.wso2.carbon.cluster.coordinator.rdbms.RDBMSMemberEventListenerTask} - Error occurred while reading membership events. java.lang.NoSuchMethodError: org.wso2.siddhi.core.stream.output.sink.SinkHandlerManager.getRegisteredSinkHandlers()Ljava/util/HashMap;
	at org.wso2.carbon.stream.processor.core.ha.HAEventListener.coordinatorChanged(HAEventListener.java:66)
```

**Suggested Labels:**
bug
**Suggested Assignees:**

**Affected Product Version:**
SP 4.1.0

**OS, DB, other environment details and versions:**    
Windows
**Steps to reproduce:**

**Related Issues:**

**Comment by dzatloukal** [comment]
I found reason of this problem. I cloned newer release of siddhi-core module from github, build that jar and put into wso2/lib/plugins folder instead the old jar file, beacuse I needed to do some changes in that module. So theese problems happens due to inconsistency of release versions of modules. After I cloned the correct release version of module, problems are gone. Closing it.
