### ISSUE TITLE
Business Rules, throw internal server error when worker not available  

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#689]
**Description:**
Business Rules, throw internal server error when worker not available   

**Steps to reproduce:**
Deploy a business rule, and try to restart the dashboard when the worker is down. 

getting the following exception 

```
JAVA_HOME environment variable is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
CARBON_HOME environment variable is set to /Users/suho/wso2/demo/sp-webinar/wso2sp-4.2.0
RUNTIME_HOME environment variable is set to /Users/suho/wso2/demo/sp-webinar/wso2sp-4.2.0/wso2/dashboard
osgi> [2018-07-09 02:04:19,586]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Endpoint Registered : /server-stats/{type}
[2018-07-09 02:04:19,606]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Endpoint Registered : /websocket-provider/{topic}
[2018-07-09 02:04:20,135]  INFO {org.wso2.msf4j.internal.websocket.WebSocketServerSC} - All required capabilities are available of WebSocket service component is available.
[2018-07-09 02:04:20,166]  INFO {org.wso2.carbon.metrics.core.config.model.JmxReporterConfig} - Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2018-07-09 02:04:20,175]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
[2018-07-09 02:04:20,178]  INFO {org.wso2.carbon.metrics.core.reporter.impl.AbstractReporter} - Started JMX reporter for Metrics
[2018-07-09 02:04:20,314]  INFO {org.wso2.msf4j.analytics.metrics.MetricsComponent} - Metrics Component is activated
[2018-07-09 02:04:20,318]  INFO {org.wso2.carbon.databridge.agent.internal.DataAgentDS} - Successfully deployed Agent Server
[2018-07-09 02:04:20,385]  INFO {org.wso2.transport.http.netty.listener.ServerConnectorBootstrap$HTTPServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9643
[2018-07-09 02:04:27,586]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Endpoint Registered : /data-provider
[2018-07-09 02:04:27,733]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary SSL Transport on port : 9714
[2018-07-09 02:04:27,734]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary TCP Transport on port : 9614
[2018-07-09 02:04:27,748]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift Server started at 0.0.0.0
[2018-07-09 02:04:27,758]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift SSL port : 7713
[2018-07-09 02:04:27,760]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift port : 7613
[2018-07-09 02:04:27,764]  INFO {org.wso2.carbon.databridge.core.internal.DataBridgeDS} - Successfully deployed Agent Server
[2018-07-09 02:04:27,946]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'portal' is available at 'https://192.168.1.2:9643/portal'.
[2018-07-09 02:04:27,970]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'business-rules' is available at 'https://192.168.1.2:9643/business-rules'.
[2018-07-09 02:04:28,344]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'policies' is available at 'https://192.168.1.2:9643/policies'.
[2018-07-09 02:04:28,351]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'monitoring' is available at 'https://192.168.1.2:9643/monitoring'.
[2018-07-09 02:04:28,378]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Stream Processor started in 10.722 sec
[2018-07-09 02:04:52,546]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.ExceptionInInitializerError
	at org.wso2.carbon.business.rules.core.api.impl.BusinessRulesApiServiceImpl.getBusinessRules(BusinessRulesApiServiceImpl.java:197)
	at org.wso2.carbon.business.rules.core.api.BusinessRulesApi.getBusinessRules(BusinessRulesApi.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: feign.RetryableException: Connection refused (Connection refused) executing GET https://localhost:9443/siddhi-apps/http-analytics_0/status
	at feign.FeignException.errorExecuting(FeignException.java:67)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:104)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy86.doGetRequest(Unknown Source)
	at org.wso2.carbon.business.rules.core.deployer.util.HTTPSClientUtil.doGetRequest(HTTPSClientUtil.java:82)
	at org.wso2.carbon.business.rules.core.deployer.SiddhiAppApiHelper.getStatus(SiddhiAppApiHelper.java:80)
	at org.wso2.carbon.business.rules.core.services.TemplateManagerService.isDeployedInNode(TemplateManagerService.java:829)
	at org.wso2.carbon.business.rules.core.services.TemplateManagerService.getSiddhiAppDeploymentState(TemplateManagerService.java:886)
	at org.wso2.carbon.business.rules.core.services.TemplateManagerService.getDeploymentState(TemplateManagerService.java:856)
	at org.wso2.carbon.business.rules.core.services.TemplateManagerService.updateStatuses(TemplateManagerService.java:820)
	at org.wso2.carbon.business.rules.core.services.TemplateManagerService.<init>(TemplateManagerService.java:76)
	at org.wso2.carbon.business.rules.core.bean.TemplateManagerInstance.<clinit>(TemplateManagerInstance.java:36)
	... 13 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at feign.Client$Default.convertResponse(Client.java:152)
	at feign.Client$Default.execute(Client.java:74)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	... 24 more

[2018-07-09 02:05:18,008]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.NoClassDefFoundError: Could not initialize class org.wso2.carbon.business.rules.core.bean.TemplateManagerInstance
	at org.wso2.carbon.business.rules.core.api.impl.BusinessRulesApiServiceImpl.getBusinessRules(BusinessRulesApiServiceImpl.java:197)
	at org.wso2.carbon.business.rules.core.api.BusinessRulesApi.getBusinessRules(BusinessRulesApi.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by minudika** [comment]
This is fixed with https://github.com/wso2/carbon-analytics/pull/1386
