### ISSUE TITLE
Rabbitmq sample does not work

### ISSUE THREAD

**Issue by AnuGayan** [wso2/product-sp#75]
when bringing up the server, this error is throwing,

Exception in thread "Timer-0" java.lang.ExceptionInInitializerError
at com.rabbitmq.client.impl.AMQConnection.defaultClientProperties(AMQConnection.java:75)
at com.rabbitmq.client.ConnectionFactory.<init>(ConnectionFactory.java:96)
at org.wso2.extension.siddhi.io.rabbitmq.sink.RabbitMQSink.connect(RabbitMQSink.java:366)
at org.wso2.siddhi.core.stream.output.sink.Sink.connectWithRetry(Sink.java:167)
at org.wso2.siddhi.core.SiddhiAppRuntime.start(SiddhiAppRuntime.java:273)
at org.wso2.carbon.stream.processor.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:71)
at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:80)
at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:159)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$6(DeploymentEngine.java:291)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:114)
at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$38(StartupComponentManager.java:250)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:236)
at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)

**Comment by tishan89** [comment]
@sivaramya Can you please look into this. And also update the ReadMe appropriately with accurate steps

**Comment by sivaramya** [comment]
Use the latest siddhi-io-rabbitmq version 1.0.4
