### ISSUE TITLE
Design view breaks when we use a custom extension

### ISSUE THREAD

**Issue by pcnfernando** [wso2/product-sp#811]
**Description:**
When we write a custom extension and use it with editor for creating a siddhi app, if we try to get the Design View, it throws the following exception.

```
[2018-09-13 13:43:41,081] ERROR {org.wso2.carbon.siddhi.editor.core.internal.EditorMicroservice} - Unable to generate design view org.wso2.siddhi.core.exception.SiddhiAppCreationException
	at org.wso2.carbon.siddhi.editor.core.util.designview.designgenerator.DesignGenerator.getEventFlow(DesignGenerator.java:54)
	at org.wso2.carbon.siddhi.editor.core.internal.EditorMicroservice.getDesignView(EditorMicroservice.java:878)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
As an improvement, it's better if we can add "Unidentified Function" or something and show the design view instead.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v4.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TanyaM** [comment]
This issue is coming in the wum updated pack and not in the vanilla pack.
