### ISSUE TITLE
Exception thrown continuously when publishing to a HA cluster, with failover configuration. 

### ISSUE THREAD

**Issue by msmshariq** [wso2/product-sp#865]
**Description:**
In the latest SP HA deployment, only the active nodes ports are open where as the passive nodes ports are closed. When configuring the receivers using failover configuration, even though the events are only published to the active node, the data-publisher tries to establish a connection with the passive node as well, since the passive nodes ports are closed, there is an exception printed in the logs continuously.

```
TID: [-1] [] [2018-11-05 07:15:57,438] ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} -  Error while trying to connect to the endpoint. Cannot borrow client for ssl://10.0.8.25:7712 {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker}
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://10.0.8.25:7712
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:136)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointSecurityException: Error while trying to connect to ssl://10.0.8.25:7712
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:81)
	at org.wso2.carbon.databridge.agent.client.AbstractClientPoolFactory.makeObject(AbstractClientPoolFactory.java:39)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:126)
	... 6 more
Caused by: org.apache.thrift.transport.TTransportException: Could not connect to 10.0.8.25 on port 7712
	at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:237)
	at org.apache.thrift.transport.TSSLTransportFactory.getClientSocket(TSSLTransportFactory.java:169)
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:64)
	... 9 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:432)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:233)
	... 11 more
```

**Suggested Labels:**
Type/Bug, Severity/Major

**Affected Product Version:**
API-M 2.6.0
API-M Analytics 2.6.0

**Steps to reproduce:**
- Create  a 2 node SP (API-M Analytics) HA cluster
- Configure even publishing in API-M with the 2 SP receivers using the failover configuration (using | as the separator) 
- Start the API-M nodes

**Comment by tishan89** [comment]
@NisalaNiroshana Any update on this?
