### ISSUE TITLE
Issue when SP node goes from passive mode to active mode in a short time interval.

### ISSUE THREAD

**Issue by msmshariq** [wso2/product-sp#916]
**Description:**
When a worker node goes into passive mode and becomes active within a short period, there can be instances where the ports are not open properly. So even though the logs say that the node is "active", the ports aren't open, hence it is not possible to publish events. 

Following exception is thrown when this issue occour; 

```
[2019-02-08 09:15:57,391] ERROR {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Error while starting binary data receiver java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:181)
	at javax.net.ssl.SSLServerSocket.<init>(SSLServerSocket.java:136)
	at sun.security.ssl.SSLServerSocketImpl.<init>(SSLServerSocketImpl.java:113)
	at sun.security.ssl.SSLServerSocketFactoryImpl.createServerSocket(SSLServerSocketFactoryImpl.java:79)
	at org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver.startSecureTransmission(BinaryDataReceiver.java:154)
	at org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver.start(BinaryDataReceiver.java:83)
	at org.wso2.carbon.stream.processor.core.ha.HAManager.changeToActive(HAManager.java:183)
	at org.wso2.carbon.stream.processor.core.ha.HAEventListener.coordinatorChanged(HAEventListener.java:106)
	at org.wso2.carbon.cluster.coordinator.rdbms.RDBMSMemberEventListenerTask.notifyCoordinatorChangeEvent(RDBMSMemberEventListenerTask.java:104)
	at org.wso2.carbon.cluster.coordinator.rdbms.RDBMSMemberEventListenerTask.run(RDBMSMemberEventListenerTask.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``` 

**Suggested Labels:**
Priority/High
Type/Bug
Severity/Critical

**Comment by DivyaPremanantha** [comment]
Fixed in https://github.com/wso2-support/carbon-analytics-common/pull/126

**Comment by DivyaPremanantha** [comment]
Fixed in https://github.com/wso2-support/carbon-analytics-common/pull/126

**Comment by minudika** [comment]
Resolved hence closing.
