### ISSUE TITLE
eree

### ISSUE THREAD

**Issue by BeParis** [wso2/product-sp#941]
**Description:**

Each time I restart wso2sp-4.4.0-alpha (which is working well after that) I get these errors:

```
[2019-03-19 10:35:31,823]  INFO {org.quartz.impl.StdSchedulerFactory} - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[2019-03-19 10:35:31,824]  INFO {org.quartz.impl.StdSchedulerFactory} - Quartz scheduler version: 2.1.1
[2019-03-19 10:35:31,824]  INFO {org.quartz.core.QuartzScheduler} - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[2019-03-19 10:35:32,361]  INFO {org.wso2.siddhi.core.aggregation.IncrementalDataPurging} - Data purging has enabled for tables: SECONDS,MINUTES,HOURS,DAYS,MONTHS,YEARS, with an interval of 3600 seconds in ESBStatAgg aggregation
[2019-03-19 10:35:32,362]  INFO {org.wso2.siddhi.core.aggregation.IncrementalDataPurging} - Data purging has enabled for tables: SECONDS,MINUTES,HOURS,DAYS,MONTHS,YEARS, with an interval of 3600 seconds in MediatorStatAgg aggregation
[2019-03-19 10:35:32,364]  INFO {org.wso2.carbon.stream.processor.core.internal.StreamProcessorService} - Siddhi App ei_analytics_statapp_0 deployed successfully
[2019-03-19 10:35:32,374]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Stream Processor started in 11.045 sec
[2019-03-19 10:35:35,552]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
[2019-03-19 10:35:35,715] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, PropertyMediator:accept_output, mediator], type=CURRENT, next=null}, as there is already an event stored with primary key 'HashCodeNullComponent'
[2019-03-19 10:35:35,716] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, DSS_PersInfos_Endpoint, endpoint], type=CURRENT, next=null}, as there is already an event stored with primary key 'HashCodeNullComponent'
[2019-03-19 10:35:35,716] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[IgnoreElement, IgnoreElement, other type], type=CURRENT, next=null}, as there is already an event stored with primary key 'IgnoreElement'
[2019-03-19 10:35:35,716] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, outAcceptSequence, sequence], type=CURRENT, next=null}, as there is already an event stored with primary key 'HashCodeNullComponent'
[2019-03-19 10:35:35,717] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, SwitchMediator, mediator], type=CURRENT, next=null}, as there is already an event stored with primary key 'HashCodeNullComponent'
[2019-03-19 10:35:35,717] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, PropertyMediator:messageType, mediator], type=CURRENT, next=null}, as there is already an event stored with primary key 'HashCodeNullComponent'
[2019-03-19 10:35:35,717] ERROR {org.wso2.siddhi.core.table.holder.IndexEventHolder} - Siddhi App 'ei_analytics_statapp_0' table 'ComponentNameInMemoryTable' dropping event : StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, HeaderMediator:Content-Type, mediator], type=CURRENT, next=null}, as there is already an event stored with primary key 'HashCodeNullComponent'
[2019-03-19 10:35:35,746] ERROR {org.wso2.siddhi.core.stream.StreamJunction} - Error in 'ei_analytics_statapp_0' after consuming events from Stream 'ComponentNameTableStream', Error in adding events to 'ComponentNameTable' store: Duplicate entry 'HashCodeNullComponent' for key 'PRIMARY'. Hence, dropping event 'StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, inAcceptSequence, sequence], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, PropertyMediator:accept_output, mediator], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, DSS_PersInfos_Endpoint, endpoint], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[IgnoreElement, IgnoreElement, other type], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[IgnoreElement, IgnoreElement, other type], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, outAcceptSequence, sequence], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, SwitchMediator, mediator], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, PropertyMediator:messageType, mediator], type=CURRENT, next=StreamEvent{ timestamp=1552988104867, beforeWindowData=null, onAfterWindowData=null, outputData=[HashCodeNullComponent, HeaderMediator:Content-Type, mediator], type=CURRENT, next=null}}}}}}}}}' org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Error in adding events to 'ComponentNameTable' store: Duplicate entry 'HashCodeNullComponent' for key 'PRIMARY'
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:585)
	at org.wso2.siddhi.core.table.record.AbstractRecordTable.add(AbstractRecordTable.java:98)
	at org.wso2.siddhi.core.table.Table.addEvents(Table.java:139)`

```

**Suggested Labels:**
Duplicate entry 'HashCodeNullComponent' error on startup

**Suggested Assignees:**

**Affected Product Version:**
wso2sp-4.4.0-alpha

**OS, DB, other environment details and versions:**    
Debian 4.9.65
DB is mySQL
Only worker is running from wso2sp-4.4.0-alpha, and "ei_analytics_statapp_0" is the only one deployed siddhy app.

**Steps to reproduce:**

**Related Issues:**

**Comment by Niveathika92** [comment]
@BeParis We have identified the issue and fixed it with https://github.com/wso2/analytics-solutions/pull/266
The fix should be available in SP 4.4.0 RC2
