### ISSUE TITLE
Errors on start and setup of EI_Analytics_StatApp under wso2sp-4.4.0-beta2

### ISSUE THREAD

**Issue by BeParis** [wso2/product-sp#948]
**Description:**
After having tested EI_Analytics_StatApp.siddhi in former SP4 alpha version (ws running well)
I dropped all tables in EI_Analytics DB then launched  this SP4 beta version with option 
`-Dfile=/opt/wso2/sp/wso2sp-4.4.0-beta2/wso2/worker/deployment/siddhi-files/EI_Analytics_StatApp.siddhi`

I got lot of errors
`[2019-03-25 13:47:48,148]  INFO {org.wso2.msf4j.MicroservicesRunner} - Microservices server started in 214ms
[2019-03-25 13:47:48,157]  INFO {org.wso2.msf4j.MicroservicesRunner} - Microservices server started in 223ms
[2019-03-25 13:47:48,191]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 7443 and port 7443
[2019-03-25 13:47:48,194]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 7070 and port 7070
[2019-03-25 13:47:48,243]  INFO {org.wso2.carbon.stream.processor.statistics.api.StatisticsApi} - org.wso2.carbon.stream.processor.statistics.api.StatisticsApi service component has  started.
[2019-03-25 13:47:48,262]  INFO {org.wso2.carbon.stream.processor.statistics.internal.service.OperatingSystemMetricsServiceComponent} - OperatingSystemMetricsService Component activated
[2019-03-25 13:47:48,379]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiverServiceComponent} - org.wso2.carbon.databridge.receiver.binary.internal.Service Component is activated
[2019-03-25 13:47:48,440]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary SSL Transport on port : 9712
[2019-03-25 13:47:48,462]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary TCP Transport on port : 9612
[2019-03-25 13:47:48,465]  INFO {org.wso2.carbon.databridge.receiver.thrift.internal.ThriftDataReceiverDS} - Service Component is activated
[2019-03-25 13:47:48,525] ERROR {org.wso2.extension.siddhi.io.mgwfile.task.MGWFileCleanUpTask} - Error occurred while cleaning the uploaded usage data. org.wso2.extension.siddhi.io.mgwfile.exception.MGWFileSourceException: Error occurred while deleting old uploaded files.
        at org.wso2.extension.siddhi.io.mgwfile.dao.MGWFileSourceDAO.deleteProcessedOldFiles(MGWFileSourceDAO.java:257)
        at org.wso2.extension.siddhi.io.mgwfile.task.MGWFileCleanUpTask.run(MGWFileCleanUpTask.java:66)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.sql.SQLSyntaxErrorException: Table 'WSO2EI_ANALYTICS_WKR_MGW_ANALYTICS_DB.AM_USAGE_UPLOADED_FILES' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1109)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1057)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1377)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1042)
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
        at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeUpdate(HikariPreparedStatementProxy.java)
        at org.wso2.extension.siddhi.io.mgwfile.dao.MGWFileSourceDAO.deleteProcessedOldFiles(MGWFileSourceDAO.java:247)
        ... 3 more

[2019-03-25 13:47:48,537]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift Server started at 0.0.0.0
[2019-03-25 13:47:48,584]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift SSL port : 7712
[2019-03-25 13:47:48,605]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift port : 7612
[2019-03-25 13:47:49,571]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
[2019-03-25 13:47:49,594]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 9443 and port 9443
[2019-03-25 13:47:49,610]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 9090 and port 9090
[2019-03-25 13:47:49,644]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Stream Processor started in 10.486 sec
[2019-03-25 13:48:10,540]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
[2019-03-25 13:48:10,594] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} - Dropping wrongly formatted event sent org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.esb.analytics.stream.FlowEntry:1.0.0 of event bundle with events 1
        at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:188)
        at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
        at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:80)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.core.exception.EventConversionException: No StreamDefinition for streamId org.wso2.esb.analytics.stream.FlowEntry:1.0.0 present in cache
        at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:171)
        ... 7 more

[2019-03-25 13:48:10,595] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} - Dropping wrongly formatted event sent org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.esb.analytics.stream.FlowEntry:1.0.0 of event bundle with events 4

etc. etc.
`

**Suggested Labels:**
Errors on start and setup of EI_Analytics_StatApp under wso2sp-4.4.0-beta2

**Suggested Assignees:**

**Affected Product Version:**
EI_Analytics_StatApp under wso2sp-4.4.0-beta2

**OS, DB, other environment details and versions:**    
> Debian 4.9.65-3+deb9u1
> mysql

**Steps to reproduce:**
- create empty DB for EI_Analytics_StatApp
- start worker of wso2sp-4.4.0-beta2 with -Dfile= ....   /EI_Analytics_StatApp.siddhi

**Related Issues:**

**Comment by BeParis** [comment]
does NOT have these errors when not using option -Dfile=path_to_siddhi_file
So I have to delete all siddhi_files from siddhi-files directory but the one I need.

**Comment by Niveathika92** [comment]
@BeParis We have identified the issue and fixed it in SP 4.4.0 RC2 with https://github.com/wso2/analytics-solutions/pull/266
Thanks for contributing!
